
import type { Metadata } from "next";

import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import 'react-toastify/dist/ReactToastify.css';
import { AuthProvider } from "./Provider";
import { InputProvider } from "./inputContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "์NEW BLOG",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <InputProvider>
  
              <Navbar/>
            {children}
          </InputProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
